### ISSUE TITLE
你好,请问在MainActivity里setExitSharedElementCallback是做什么的

### ISSUE THREAD

**Issue by XhinLiang** [oxoooo/mr-mantou-android#1]

**Comment by xingrz** [comment]
Shared Element Transition 相关

因为 ViewerActivity 里的图片位于 Fragment 中，返回 MainActivity 时框架无法正确侦测到 Shared Element 对应关系，所以要自己写逻辑去映射。

**Comment by XhinLiang** [comment]
非常感谢
