### ISSUE TITLE
Error:(24, 0) For input string: ""

### ISSUE THREAD

**Issue by ylmyg** [oxoooo/mr-mantou-android#11]
Error:(24, 0) For input string: ""
我想请问下，出现这个错误是什么意思？

**Comment by xingrz** [comment]
地址要自己填，在build.prop里。

**Comment by ylmyg** [comment]
不是很明白，是要填什么？我把它删掉了..

**Comment by xingrz** [comment]
哦懂了，原来是git的那个报错啊…
你肯定是没用git直接下载代码zip的。

**Comment by ylmyg** [comment]
我再看下吧~ 好多报错哦~
