### ISSUE TITLE
兄弟

### ISSUE THREAD

**Issue by sunreview** [oxoooo/mr-mantou-android#13]
你的项目打不开，加下我qq 1402709211，你把项目发给我，有偿的，谢谢。

**Comment by xingrz** [comment]
本项目已废弃，不再提供任何技术支持。

**Comment by sunreview** [comment]
发一下呗，我给你150元作为感谢。

**Comment by xingrz** [comment]
我不知道你所说的「发一下」的项目是哪个项目。这个仓库就包含了这个项目所有的最新的源码。

**Comment by sunreview** [comment]
你的项目打不开，你能不能换个电脑编译下，拜托了。看你的项目源码很简单，应该不会找到这么简单的meizhi应用了
