### ISSUE TITLE
请问图片抓自哪里？程序哪个部分是定义抓图地址的？

### ISSUE THREAD

**Issue by saa350** [oxoooo/mr-mantou-android#3]

**Comment by fuxuemingzhu** [comment]
应该是 http://gank.io/

**Comment by xingrz** [comment]
- 数据主要来自于 [gank.io](http://gank.io)
- 本 App 所有数据托管在我们自己的 LeanCloud 后端上，不直接请求 gank.io
- 所以没有哪个部分定义了抓图地址
