### ISSUE TITLE
insets控件的说明

### ISSUE THREAD

**Issue by hedan806** [oxoooo/mr-mantou-android#6]
可以说明一下自定义insets控件的工作流程，自己原理吗？代码小白提问，问得有误，还请见谅～

**Comment by xingrz** [comment]
目前的实现是这样的：

首先 insets 的含义是应用被系统控件（比如状态栏和导航栏）遮盖了多少

`InsetsCoodinatorLayout` 是最顶层的容器，它通过 [`ViewCompat.setOnApplyWindowInsetsListener`](https://github.com/oxoooo/mr-mantou-android/blob/fde5949fc9da37227760d39fe25cb0bd0f291c4b/app/src/main/java/ooo/oxo/mr/widget/InsetsCoordinatorLayout.java#L43) 接收到系统告诉它的 insets，然后将它们发给自己的子控件

为了兼容 Android 4.4 的旧 API，我还覆盖了 [`fitSystemWindows`](https://github.com/oxoooo/mr-mantou-android/blob/fde5949fc9da37227760d39fe25cb0bd0f291c4b/app/src/main/java/ooo/oxo/mr/widget/InsetsCoordinatorLayout.java#L71) 来模拟类似的功能

**Comment by hedan806** [comment]
嗯，大概了解了。

可是我照着写出来后，在toolbar的上面有一个状态栏高度的透明区域。

并且，在手指按住滑动时不会隐藏，只有在手指松开后，才往上隐藏。

另外，那个WindowInsetsHandle接口，好像没调用上。

这会是什么原因呢。手机没法上图～
