### ISSUE TITLE
编译不过啊

### ISSUE THREAD

**Issue by leach-chen** [oxoooo/mr-mantou-android#7]
def gitCommits = Integer.parseInt('git rev-list --count HEAD'.execute([], project.rootDir).text.trim())

在builde.gradle里面这行 Error:(24, 1) A problem occurred evaluating project ':app'.

> For input string: ""

**Comment by xingrz** [comment]
那就去掉它

**Comment by leach-chen** [comment]
去掉也没用

**Comment by asmallkite** [comment]
我也遇到这个问题

**Comment by xingrz** [comment]
确定你的项目是 clone 下来的而不是下载 zip 包的？

**Comment by asmallkite** [comment]
当我clone的时候，会弹出这样的错误，只能下载zip包了
![wua cz5i27u fvjl mzkym](https://cloud.githubusercontent.com/assets/16522557/19067945/fe3da842-8a52-11e6-8c35-c4ae063884cb.png)
@xingrz

**Comment by asmallkite** [comment]
将build.gradle中的grale版本升级后解决了
 classpath 'com.android.tools.build:gradle:2.2.0'
